SELECT
    COUNT(DISTINCT(CUSTOMER.C_CUSTKEY))
FROM CUSTOMER
JOIN ORDERS ON
    CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
WHERE 
    ORDERS.O_COMMENT LIKE "%special request%" AND
    CUSTOMER.C_CUSTKEY NOT IN (
        SELECT
            DISTINCT(CUSTOMER.C_CUSTKEY)
        FROM CUSTOMER
        JOIN ORDERS ON
            CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
        WHERE ORDERS.O_COMMENT LIKE "%unusual package%"
    )
;